//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.Localization.Resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Example.Localization.Resource.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample1 {
            get {
                return ResourceManager.GetString("Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample1C1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample1C1 {
            get {
                return ResourceManager.GetString("Sample1C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample1C2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample1C2 {
            get {
                return ResourceManager.GetString("Sample1C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample1C2C1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample1C2C1 {
            get {
                return ResourceManager.GetString("Sample1C2C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample 1 Child-1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample1Child1 {
            get {
                return ResourceManager.GetString("Sample1Child1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample 1 Child 2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample1Child2 {
            get {
                return ResourceManager.GetString("Sample1Child2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample 1 Child 2 Sub 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample1Child2Sub1 {
            get {
                return ResourceManager.GetString("Sample1Child2Sub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample 1 Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sample1Page {
            get {
                return ResourceManager.GetString("Sample1Page", resourceCulture);
            }
        }
    }
}
