// ReSharper disable UnusedMember.Global
#pragma warning disable CS1591
using BlazorPathHelper;

/// <summary>
/// pre-defined paths for blazor webpages
/// </summary>
/// <remarks>
/// this file is auto-generated by BlazorPathHelper.Generator. <br/>
/// documentation: https://github.com/arika0093/BlazorPathHelper/blob/main/README.md
/// </remarks>
[BlazorPath]
public partial class WebPaths
{
    [Item("Top Page")]
    public const string Index = "/";
    [Item("Sample Page")]
    public const string Sample = "/sample";
    [Item("Sample Page - Child")]
    public const string SampleChild = "/sample/child";
    [Item("Counter Page")]
    public const string Counter = "/counter";
    public const string CounterWithState = "/counter/{count:int}";
}
