name: mkdocs publish action
on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r mkdocs.requirements.txt
      
      - name: Use nbgv
        uses: dotnet/nbgv@master
        id: nbgv

      - name: Build Docs Website
        run: mike deploy --push ${{ steps.nbgv.outputs.NuGetPackageVersion }} 

      - name: Mark current deployment as dev
        run: mike set dev --push

      - name: Delete Old Prerelease Versions
        run: mike remove --push $(mike list | grep -v latest | grep -v dev | grep alpha) 
