name: .NET Build, Test, and Publish

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - '**.csproj'
      - '**.cs'
      - '**.yaml'
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
          cache: true
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Run tests
        run: dotnet test --no-build -c Release --verbosity normal

      - name: Generate Nuget Package
        run: dotnet pack --no-build -c Release --output ./artifacts
        
      - name: Publish Nuget Package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json  